import Image from 'next/image';
import { SectionHeading } from '@hitech/ui';
import { Breadcrumbs, PageIntro, QuoteCta, TextLink } from '@/components/common';
import { pageMetadata } from '@/lib/metadata';

export const metadata = pageMetadata('About Us', 'Hitech Lab & Surgical Solutions supports laboratory and diagnostic procurement for healthcare, research and educational institutions.', '/about');
export default function AboutPage() {
  return <><div className="page-banner"><div className="container"><Breadcrumbs items={[{label:'About Us'}]} /><PageIntro eyebrow="ABOUT HITECH" title="Behind every laboratory, a world of possibility.">We supply the everyday essentials and specialised products that support healthcare, research and education.</PageIntro></div></div><section className="container about-split"><div className="about-image"><Image loading="eager" src="/images/laboratory.webp?view=about" alt="Illustrative microscope and glassware in a modern laboratory setting" fill sizes="(max-width: 700px) 90vw, 45vw" /><span className="image-caption">Illustrative laboratory image</span></div><div className="about-copy"><SectionHeading eyebrow="A FOCUSED SUPPLY PARTNER" title="Your work has a purpose. So does ours." /><p>Hitech Lab &amp; Surgical Solutions focuses on supplying dependable laboratory and diagnostic products to healthcare, research and educational institutions.</p><p>Our range brings together laboratory equipment, consumables, reagents, sample collection products and selected surgical supplies. We help institutional buyers organise their requirements and enquire about the product details that matter.</p><p>It starts with a clear conversation: what you need, the quantities you require and the specifications your facility works with.</p><TextLink href="/products">Discover our product range</TextLink></div></section><section className="why-section"><div className="container"><SectionHeading eyebrow="HOW WE APPROACH OUR WORK" title="Clarity at every step." /><div className="principles-grid">{[{title:'Requirements come first',text:'We start with your facility’s needs, from routine replenishment to a more specific product enquiry.'},{title:'Details deserve attention',text:'Brands, formats, pack sizes and compatibility should be confirmed before an order is agreed.'},{title:'A practical partnership',text:'One point of contact for discussing your laboratory and diagnostic supply requirements.'}].map((item,index) => <div className="principle" key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></div>)}</div></div></section><div className="h-16" /><QuoteCta /><div className="h-16" /></>;
}
