import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Boxes, FlaskConical, Microscope, PackageCheck, Headset, ClipboardList, Hospital, GraduationCap, Building2, TestTubes, Dna, Stethoscope, Pill } from 'lucide-react';
import { SectionHeading } from '@hitech/ui';
import { categories } from '@/data/categories';
import { getFeaturedProducts } from '@/services/catalog';
import { ProductCard } from '@/components/product-card';
import { QuoteCta, TextLink } from '@/components/common';
import { ContactDetails } from '@/components/footer';
import { pageMetadata } from '@/lib/metadata';

export const metadata = pageMetadata('Laboratory & Diagnostic Supplies', 'Explore laboratory equipment, consumables, diagnostic reagents and scientific supplies from Hitech Lab & Surgical Solutions. Request a B2B quotation.', '/');
const categoryIcons = [Microscope, TestTubes, FlaskConical, ClipboardList, TestTubes, FlaskConical, Dna, FlaskConical, Boxes, Stethoscope];
const values = [
  { icon: Boxes, title: 'A considered product range', text: 'Equipment, consumables and diagnostic supplies, brought together for simpler sourcing.' },
  { icon: PackageCheck, title: 'Supply with clarity', text: 'Discuss availability, brands and specifications before you place your order.' },
  { icon: ClipboardList, title: 'Procurement that fits', text: 'Share your requirements, quantities and preferred formats for a tailored quotation.' },
  { icon: Headset, title: 'A team you can talk to', text: 'Get support with product enquiries and the details that matter to your facility.' },
];

export default function Home() {
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-content"><p className="eyebrow"><span className="eyebrow-line" />LABORATORY &amp; DIAGNOSTIC SUPPLIES</p><h1>Reliable supplies.<br />For the science<br /><span>that matters.</span></h1><p className="hero-description">From everyday lab essentials to specialised diagnostic products. Supporting the people who move healthcare and research forward.</p><div className="button-row"><Link className="button button-primary" href="/products">Explore Products <ArrowRight size={18} aria-hidden="true" /></Link><Link className="button button-outline" href="/contact">Request a Quote <ArrowUpRight size={18} aria-hidden="true" /></Link></div><div className="hero-note"><span className="small-icon"><FlaskConical size={18} aria-hidden="true" /></span>Built around your laboratory’s needs.</div></div><div className="hero-visual"><Image src="/images/laboratory.webp?view=hero" alt="Illustrative modern microscope and laboratory glassware on a blue laboratory bench" fill sizes="(max-width: 900px) 100vw, 52vw" loading="eager" fetchPriority="high" className="hero-image" /><div className="hero-image-label"><span>PRECISION IN EVERY REQUIREMENT</span><p>Your work matters.<br />So do your supplies.</p></div><span className="hero-image-caption">Illustrative laboratory image</span></div></div></section>
    <div className="audience-strip"><div className="container"><span>SUPPORTING YOUR WORK IN</span><p><Microscope size={19} aria-hidden="true" />Laboratories</p><p><Hospital size={19} aria-hidden="true" />Healthcare</p><p><GraduationCap size={21} aria-hidden="true" />Research &amp; education</p><p><Dna size={20} aria-hidden="true" />Life sciences</p></div></div>
    <section className="section container"><div className="section-top"><SectionHeading eyebrow="OUR PRODUCT RANGE" title="Everyday essentials. Specialised solutions.">Find the supplies your facility needs, all in one place.</SectionHeading><TextLink href="/products">View all products</TextLink></div><div className="category-feature-grid">{categories.slice(0,3).map((category, index) => <Link href={`/products?category=${category.id}`} className="category-feature" key={category.id}><div className="category-feature-image"><Image src={category.image} alt={`Illustrative ${category.shortName.toLowerCase()} collection`} fill sizes="(max-width: 650px) 90vw, 33vw" /><span className="category-number">0{index+1}</span></div><div className="category-feature-copy"><h3>{category.name}</h3><p>{category.description}</p><span className="circle-arrow"><ArrowUpRight size={20} aria-hidden="true" /></span></div></Link>)}</div><div className="category-mini-grid">{categories.slice(3).map((category,index) => {const Icon = categoryIcons[index+3];return <Link className="category-mini" key={category.id} href={`/products?category=${category.id}`}><Icon size={22} aria-hidden="true" /><span>{category.name}</span><ArrowUpRight size={16} aria-hidden="true" /></Link>;})}</div><p className="caption-note">Category imagery is illustrative. Ask our team for exact product photographs.</p></section>
    <section className="why-section"><div className="container why-grid"><div><SectionHeading eyebrow="THE HITECH APPROACH" title="Good science needs a dependable supply partner.">We focus on the details of procurement, so you can focus on the work in front of you.</SectionHeading><TextLink href="/about">Get to know Hitech</TextLink></div><div className="values-grid">{values.map(value => <div className="value-item" key={value.title}><value.icon size={26} strokeWidth={1.5} aria-hidden="true" /><h3>{value.title}</h3><p>{value.text}</p></div>)}</div></div></section>
    <section className="section container"><div className="section-top"><SectionHeading eyebrow="EXPLORE THE CATALOGUE" title="Essentials for your laboratory.">A selection from our equipment, consumables and reagent range.</SectionHeading><TextLink href="/products">Browse catalogue</TextLink></div><div className="product-grid featured-grid">{getFeaturedProducts().map(product => <ProductCard product={product} key={product.id} />)}</div></section>
    <section className="industries-home section container"><div className="section-top"><SectionHeading eyebrow="INDUSTRIES WE SERVE" title="Different disciplines. Shared standards.">Supporting procurement across healthcare, science and education.</SectionHeading><TextLink href="/industries">Explore industries</TextLink></div><div className="industry-strip">{[{icon:Microscope,name:'Diagnostic laboratories'},{icon:Hospital,name:'Hospitals'},{icon:Stethoscope,name:'Clinics'},{icon:Dna,name:'Research laboratories'},{icon:GraduationCap,name:'Colleges & universities'},{icon:Pill,name:'Pharmaceutical companies'},{icon:Building2,name:'Healthcare institutions'}].map(item => <Link href="/industries" className="industry-tile" key={item.name}><item.icon size={29} strokeWidth={1.4} aria-hidden="true" /><h3>{item.name}</h3></Link>)}</div></section>
    <QuoteCta /><section className="container contact-band"><div><p className="eyebrow">HAVE A SPECIFIC REQUIREMENT?</p><h2>Let’s find what your facility needs.</h2><ContactDetails /></div><TextLink href="/contact">Talk to our team</TextLink></section>
  </>;
}
